# In db-interact/.github/workflows/ci-cd.yml
name: DB-Interact Service CI/CD (Test, Build, Push)

on:
  push:
    branches:
      - main # Or your primary branch
  workflow_dispatch: # Allows manual triggering

jobs:
  test-db-interact: # Renamed job for clarity
    runs-on: ubuntu-latest
    name: Run DB-Interact Unit Tests
    steps:
      - name: Checkout db-interact source code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Matches your Dockerfile

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # If your tests have specific dependencies not in the main requirements.txt,
          # (e.g., pytest, pytest-mock if not already included for the app)
          # consider adding them to requirements.txt or a separate requirements-test.txt
          # pip install pytest pytest-mock # Example if not in requirements.txt

      - name: Run Pytest for db-interact
        run: |
          pytest tests/ # Assumes your tests are in the 'tests' directory
          # You can add options like:
          # pytest tests/ -v --cov=db_interact_service --cov-report=xml

  build-and-push-db-interact: # Renamed job for clarity
    runs-on: ubuntu-latest
    name: Build & Push DB-Interact Docker Image
    needs: test-db-interact # Depends on the successful completion of the test job
    env:
      DOCKER_IMAGE_NAME: mariuspreda/db-interact # Updated Docker image name

    steps:
      - name: Checkout db-interact source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub PAT

      - name: Build and push Docker image (multi-platform)
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build from the root of the db-interact repo
          file: ./Dockerfile # Path to your Dockerfile in db-interact repo
          platforms: linux/amd64,linux/arm64 
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} 
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
