# In db-interact/.github/workflows/ci-cd.yml
name: DB-Interact Service CI (Build & Push to Docker Hub)

on:
  push:
    branches:
      - main # Or your primary branch
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-push-db-interact:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE_NAME: mariuspreda/db-interact # Your Docker Hub image name for this service

    steps:
      - name: Checkout db-interact source code
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Docker Hub PAT

      - name: Build and push Docker image (multi-platform)
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build from the root of the db-interact repo
          file: ./Dockerfile # Path to your Dockerfile in db-interact repo
          platforms: linux/amd64,linux/arm64 # Build for both architectures
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }} # Also push a SHA-tagged version for reference
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

